# Name of workflow
name: Node CI

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

jobs:
  build:

  steps:
    - name: Run linter
        # Run Linter
        run: |
          make lint
          